[2023-12-15 23:11:30,518: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 23:11:30,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 23:11:30,539: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-15 23:11:30,539: INFO: common: created directory at: artifacts]
[2023-12-15 23:16:37,214: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 23:16:37,214: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 23:16:37,219: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-15 23:16:37,219: INFO: common: created directory at: artifacts]
[2023-12-15 23:18:26,510: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 23:18:26,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 23:18:26,526: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-15 23:18:26,532: INFO: common: created directory at: artifacts]
[2023-12-15 23:18:26,532: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-15 23:18:28,256: INFO: 2353853782: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C5A0:3EDF:58A480:6C0755:657C916A
Accept-Ranges: bytes
Date: Fri, 15 Dec 2023 17:48:27 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10238-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1702662507.644277,VS0,VE787
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 599b9b0ac4f7e148352aa43892a0cb8e77ce60d3
Expires: Fri, 15 Dec 2023 17:53:27 GMT
Source-Age: 0

]
[2023-12-30 00:47:00,512: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-30 00:47:00,513: ERROR: main: name 'DataIngestionTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 6, in <module>
    data_ingestion = DataIngestionTrainingPipeline()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'DataIngestionTrainingPipeline' is not defined
[2023-12-30 00:47:36,027: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-30 00:47:36,036: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-30 00:47:36,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-30 00:47:36,042: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-30 00:47:36,043: INFO: common: created directory at: artifacts]
[2023-12-30 00:47:36,044: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-30 00:47:38,810: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 7E02:04A0:76064A:90A0B0:658F1B51
Accept-Ranges: bytes
Date: Fri, 29 Dec 2023 19:17:38 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10243-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1703877457.941676,VS0,VE1546
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: f0217e8d52748f76516ecd013f439405caa16827
Expires: Fri, 29 Dec 2023 19:22:38 GMT
Source-Age: 0

]
[2023-12-30 00:47:38,827: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-30 00:49:10,392: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-30 00:49:10,394: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-30 00:49:10,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-30 00:49:10,396: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-30 00:49:10,399: INFO: common: created directory at: artifacts]
[2023-12-30 00:49:10,399: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-30 00:49:11,494: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 7E02:04A0:76064A:90A0B0:658F1B51
Accept-Ranges: bytes
Date: Fri, 29 Dec 2023 19:19:11 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10251-MAA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1703877551.198617,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c875d4a20a235a6698512f5890bced71529300ec
Expires: Fri, 29 Dec 2023 19:24:11 GMT
Source-Age: 93

]
[2023-12-30 00:49:11,506: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-30 03:10:06,289: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-30 03:10:06,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-30 03:10:06,291: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-30 03:10:06,296: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-30 03:10:06,297: INFO: common: created directory at: artifacts]
[2023-12-30 03:10:06,297: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-30 03:10:08,471: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 998C:5B9B:6E2FC4:8BC3A5:658F3CB6
Accept-Ranges: bytes
Date: Fri, 29 Dec 2023 21:40:08 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10240-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1703886007.197424,VS0,VE957
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: e842fd95adcc355dc4105b408f88a3eaff06f735
Expires: Fri, 29 Dec 2023 21:45:08 GMT
Source-Age: 1

]
[2023-12-30 03:10:08,485: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-31 04:00:19,781: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 04:00:19,789: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 04:00:19,801: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 04:00:19,804: INFO: common: created directory at: artifacts]
[2023-12-31 04:00:19,805: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 13:55:24,065: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 13:55:24,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 13:55:24,081: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 13:55:24,081: INFO: common: created directory at: artifacts]
[2023-12-31 13:55:24,081: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 14:00:09,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:00:09,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:00:09,623: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 14:00:09,625: INFO: common: created directory at: artifacts]
[2023-12-31 14:00:09,628: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 14:01:36,035: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:01:36,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:01:36,052: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 14:01:36,057: INFO: common: created directory at: artifacts]
[2023-12-31 14:01:36,057: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 14:03:35,419: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:03:35,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:03:35,428: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 14:03:35,430: INFO: common: created directory at: artifacts]
[2023-12-31 14:03:35,430: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 14:11:31,460: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:11:31,463: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:11:31,467: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 14:11:31,470: INFO: common: created directory at: artifacts]
[2023-12-31 14:11:31,472: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 14:16:23,023: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:16:23,023: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 14:16:23,031: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 14:16:23,036: INFO: common: created directory at: artifacts]
[2023-12-31 14:16:23,036: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 17:52:10,624: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 17:52:10,627: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 17:52:10,639: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 17:52:10,641: INFO: common: created directory at: artifacts]
[2023-12-31 17:52:10,643: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 18:01:31,193: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 18:01:31,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 18:01:31,201: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 18:01:31,202: INFO: common: created directory at: artifacts]
[2023-12-31 18:01:31,204: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 19:33:01,801: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 19:33:01,803: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 19:33:01,807: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 19:33:01,807: INFO: common: created directory at: artifacts]
[2023-12-31 19:33:01,812: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 19:43:03,953: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 19:43:03,956: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 19:43:03,965: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 19:43:03,968: INFO: common: created directory at: artifacts]
[2023-12-31 19:43:03,970: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-31 19:52:31,426: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 19:52:31,429: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 19:52:31,430: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 19:52:31,435: INFO: common: created directory at: artifacts]
[2023-12-31 19:52:31,437: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 20:21:40,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:21:40,844: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:21:40,847: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 20:21:40,849: INFO: common: created directory at: artifacts]
[2023-12-31 20:21:40,850: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 20:22:51,288: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:22:51,291: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:22:51,295: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 20:22:51,297: INFO: common: created directory at: artifacts]
[2023-12-31 20:22:51,299: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 20:25:31,635: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:25:31,639: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:25:31,643: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 20:25:31,645: INFO: common: created directory at: artifacts]
[2023-12-31 20:25:31,647: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 20:26:04,583: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:26:04,585: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:26:04,588: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 20:26:04,588: INFO: common: created directory at: artifacts]
[2023-12-31 20:26:04,594: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 20:26:25,506: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:26:25,510: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:26:25,513: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 20:26:25,516: INFO: common: created directory at: artifacts]
[2023-12-31 20:26:25,518: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 20:27:14,111: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:27:14,115: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:27:14,119: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 20:27:14,122: INFO: common: created directory at: artifacts]
[2023-12-31 20:27:14,123: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 20:49:24,568: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:49:24,571: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:49:24,575: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 20:49:24,576: INFO: common: created directory at: artifacts]
[2023-12-31 20:49:24,578: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 20:53:34,837: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:53:34,840: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:53:34,843: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 20:53:34,846: INFO: common: created directory at: artifacts]
[2023-12-31 20:53:56,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:53:56,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 20:53:56,534: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 20:53:56,536: INFO: common: created directory at: artifacts]
[2023-12-31 21:06:42,328: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 21:06:42,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 21:06:42,338: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 21:06:42,340: INFO: common: created directory at: artifacts]
[2023-12-31 21:08:03,081: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 21:08:03,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 21:08:03,083: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 21:08:03,091: INFO: common: created directory at: artifacts]
[2023-12-31 21:12:24,631: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 21:12:24,634: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 21:12:24,638: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 21:12:24,640: INFO: common: created directory at: artifacts]
[2023-12-31 21:12:24,641: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 22:15:37,500: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 22:15:37,505: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 22:15:37,516: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 22:15:37,521: INFO: common: created directory at: artifacts]
[2023-12-31 22:15:37,521: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 22:41:52,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 22:41:52,462: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 22:41:52,470: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 22:41:52,470: INFO: common: created directory at: artifacts]
[2023-12-31 22:41:52,478: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 23:22:58,125: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:22:58,127: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:22:58,132: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 23:22:58,134: INFO: common: created directory at: artifacts]
[2023-12-31 23:22:58,135: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 23:24:02,537: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:24:02,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:24:02,546: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 23:24:02,549: INFO: common: created directory at: artifacts]
[2023-12-31 23:24:02,550: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 23:25:22,716: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:25:22,720: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:25:22,732: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 23:25:22,732: INFO: common: created directory at: artifacts]
[2023-12-31 23:25:22,732: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 23:53:50,679: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:53:50,682: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:53:50,685: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 23:53:50,687: INFO: common: created directory at: artifacts]
[2023-12-31 23:53:50,688: INFO: common: created directory at: artifacts/data_validation]
[2023-12-31 23:54:10,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:54:10,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-31 23:54:10,079: INFO: common: yaml file: schema.yaml loaded successfully]
[2023-12-31 23:54:10,081: INFO: common: created directory at: artifacts]
[2023-12-31 23:54:10,082: INFO: common: created directory at: artifacts/data_validation]
[2024-01-01 00:04:47,135: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 00:04:47,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 00:04:47,142: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 00:04:47,144: INFO: common: created directory at: artifacts]
[2024-01-01 00:04:47,146: INFO: common: created directory at: artifacts/data_validation]
[2024-01-01 00:19:17,901: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-01 00:19:17,901: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-01 00:19:18,834: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-01 00:19:18,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 00:19:18,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 00:19:18,834: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 00:19:18,834: INFO: common: created directory at: artifacts]
[2024-01-01 00:19:18,834: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-01 00:19:20,968: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 710E:36B2:B6C4FE:E54D25:6591B7AD
Accept-Ranges: bytes
Date: Sun, 31 Dec 2023 18:49:19 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10246-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1704048559.315369,VS0,VE317
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: fbc372783461699383e084e1842d936a7c91f482
Expires: Sun, 31 Dec 2023 18:54:19 GMT
Source-Age: 0

]
[2024-01-01 00:19:20,999: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-01 00:19:20,999: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-01 00:19:20,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 00:19:20,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 00:19:21,015: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 00:19:21,015: INFO: common: created directory at: artifacts]
[2024-01-01 00:19:21,015: INFO: common: created directory at: artifacts/data_validation]
[2024-01-01 00:19:21,093: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-01 02:45:37,239: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:45:37,242: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:45:37,247: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 02:45:37,250: INFO: common: created directory at: artifacts]
[2024-01-01 02:45:37,252: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 02:46:24,612: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:46:24,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:46:24,618: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 02:46:24,620: INFO: common: created directory at: artifacts]
[2024-01-01 02:46:24,622: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 02:50:14,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:50:14,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:50:14,402: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 02:50:14,404: INFO: common: created directory at: artifacts]
[2024-01-01 02:50:14,406: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 02:50:46,052: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:50:46,055: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:50:46,059: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 02:50:46,061: INFO: common: created directory at: artifacts]
[2024-01-01 02:50:46,063: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 02:50:46,173: INFO: 732983346: Splited data into train and test sets]
[2024-01-01 02:55:30,882: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:55:30,886: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:55:30,889: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 02:55:30,890: INFO: common: created directory at: artifacts]
[2024-01-01 02:55:30,891: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 02:55:30,978: INFO: 3647971484: Splited data into train and test sets]
[2024-01-01 02:55:37,310: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:55:37,313: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:55:37,317: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 02:55:37,318: INFO: common: created directory at: artifacts]
[2024-01-01 02:55:37,320: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 02:55:37,415: INFO: 3647971484: Splited data into train and test sets]
[2024-01-01 02:55:37,882: INFO: 3647971484: Balanced the training data]
[2024-01-01 02:57:02,623: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:57:02,626: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:57:02,630: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 02:57:02,631: INFO: common: created directory at: artifacts]
[2024-01-01 02:57:02,635: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 02:57:02,692: INFO: 3689143997: Splited data into train and test sets]
[2024-01-01 02:57:02,891: INFO: 3689143997: Balanced the training data]
[2024-01-01 02:59:30,731: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:59:30,735: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 02:59:30,739: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 02:59:30,740: INFO: common: created directory at: artifacts]
[2024-01-01 02:59:30,741: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 03:00:10,311: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:00:10,314: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:00:10,317: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:00:10,319: INFO: common: created directory at: artifacts]
[2024-01-01 03:00:10,320: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 03:02:34,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:02:34,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:02:34,012: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:02:34,014: INFO: common: created directory at: artifacts]
[2024-01-01 03:02:34,015: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 03:02:52,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:02:52,077: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:02:52,080: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:02:52,082: INFO: common: created directory at: artifacts]
[2024-01-01 03:02:52,083: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 03:02:52,302: INFO: 578451359: Data split and balanced successfully.]
[2024-01-01 03:05:17,208: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:05:17,211: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:05:17,215: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:05:17,216: INFO: common: created directory at: artifacts]
[2024-01-01 03:05:17,218: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 03:05:17,428: INFO: 578451359: Data split and balanced successfully.]
[2024-01-01 03:08:54,166: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:08:54,166: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:08:54,175: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:08:54,175: INFO: common: created directory at: artifacts]
[2024-01-01 03:08:54,175: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 03:08:54,392: INFO: 2594490729: Data split and balanced successfully.]
[2024-01-01 03:09:58,019: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:09:58,019: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:09:58,027: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:09:58,029: INFO: common: created directory at: artifacts]
[2024-01-01 03:09:58,031: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 03:09:58,226: INFO: 429273344: Data split and balanced successfully.]
[2024-01-01 03:42:30,263: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-01 03:42:30,263: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-01 03:45:29,974: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-01 03:45:29,974: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-01 03:45:31,302: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-01 03:45:31,302: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:45:31,302: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:45:31,302: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:45:31,302: INFO: common: created directory at: artifacts]
[2024-01-01 03:45:31,302: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-01 03:45:33,841: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FD72:07D9:D0FA2B:1023FF3:6591E804
Accept-Ranges: bytes
Date: Sun, 31 Dec 2023 22:15:33 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10244-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1704060932.367250,VS0,VE1414
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: e233bcb8ca505f6d6bc646deedb65600bed5e60b
Expires: Sun, 31 Dec 2023 22:20:33 GMT
Source-Age: 0

]
[2024-01-01 03:45:33,857: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-01 03:45:33,857: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-01 03:45:33,857: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:45:33,857: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:45:33,857: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:45:33,857: INFO: common: created directory at: artifacts]
[2024-01-01 03:45:33,857: INFO: common: created directory at: artifacts/data_validation]
[2024-01-01 03:45:33,889: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-01 03:45:33,889: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-01 03:45:33,904: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:45:33,904: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:45:33,904: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:45:33,904: INFO: common: created directory at: artifacts]
[2024-01-01 03:45:33,904: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 03:45:33,904: ERROR: stage_03_data_transformation: An error occurred: 'DataTransformation' object has no attribute 'train_test_spliting']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_03_data_transformation.py", line 21, in main
    data_transformation.train_test_spliting()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataTransformation' object has no attribute 'train_test_spliting'
[2024-01-01 03:45:33,904: ERROR: main: An error occurred: 'DataTransformation' object has no attribute 'train_test_spliting']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 30, in <module>
    data_transformation.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_03_data_transformation.py", line 27, in main
    raise e
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_03_data_transformation.py", line 21, in main
    data_transformation.train_test_spliting()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataTransformation' object has no attribute 'train_test_spliting'
[2024-01-01 03:46:47,963: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-01 03:46:47,963: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-01 03:46:49,236: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-01 03:46:49,236: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:46:49,236: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:46:49,236: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:46:49,236: INFO: common: created directory at: artifacts]
[2024-01-01 03:46:49,236: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-01 03:46:50,009: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FD72:07D9:D0FA2B:1023FF3:6591E804
Accept-Ranges: bytes
Date: Sun, 31 Dec 2023 22:16:49 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10240-MAA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1704061010.956068,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: bfdeaa29832bb8dfb332fe3b462788357d0e8fd2
Expires: Sun, 31 Dec 2023 22:21:49 GMT
Source-Age: 77

]
[2024-01-01 03:46:50,021: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-01 03:46:50,021: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-01 03:46:50,021: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:46:50,021: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:46:50,021: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:46:50,021: INFO: common: created directory at: artifacts]
[2024-01-01 03:46:50,028: INFO: common: created directory at: artifacts/data_validation]
[2024-01-01 03:46:50,044: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-01 03:46:50,060: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-01 03:46:50,060: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:46:50,060: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 03:46:50,060: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 03:46:50,060: INFO: common: created directory at: artifacts]
[2024-01-01 03:46:50,060: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 03:46:50,496: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-01 03:46:50,496: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-01 19:32:11,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:32:11,297: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:32:11,320: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 19:32:11,324: INFO: common: created directory at: artifacts]
[2024-01-01 19:32:11,324: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 19:41:46,584: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:41:46,592: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:41:46,600: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 19:41:46,600: INFO: common: created directory at: artifacts]
[2024-01-01 19:41:46,600: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 19:43:50,181: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:43:50,184: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:43:50,187: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 19:43:50,189: INFO: common: created directory at: artifacts]
[2024-01-01 19:43:50,191: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 19:45:37,980: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:45:37,980: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:45:37,988: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 19:45:37,988: INFO: common: created directory at: artifacts]
[2024-01-01 19:45:37,988: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 19:48:02,170: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:48:02,170: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:48:02,178: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 19:48:02,178: INFO: common: created directory at: artifacts]
[2024-01-01 19:48:02,186: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 19:49:13,678: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:49:13,682: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:49:13,687: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 19:49:13,690: INFO: common: created directory at: artifacts]
[2024-01-01 19:49:13,691: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 19:50:37,734: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:50:37,738: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:50:37,741: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 19:50:37,742: INFO: common: created directory at: artifacts]
[2024-01-01 19:50:37,744: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 19:51:18,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:51:18,896: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:51:18,900: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 19:51:18,903: INFO: common: created directory at: artifacts]
[2024-01-01 19:51:18,904: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 19:52:16,906: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:52:16,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 19:52:16,914: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 19:52:16,914: INFO: common: created directory at: artifacts]
[2024-01-01 19:52:16,922: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 20:14:50,470: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-01 20:14:50,470: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-01 20:14:54,148: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-01 20:14:54,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 20:14:54,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 20:14:54,156: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 20:14:54,156: INFO: common: created directory at: artifacts]
[2024-01-01 20:14:54,156: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-01 20:14:56,189: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 18B2:3B55:11E87DB:16235E1:6592CFE7
Accept-Ranges: bytes
Date: Mon, 01 Jan 2024 14:44:56 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10229-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1704120296.798185,VS0,VE376
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 4b58fde4c86c1e6fb832729a0684a8a67af935aa
Expires: Mon, 01 Jan 2024 14:49:56 GMT
Source-Age: 0

]
[2024-01-01 20:14:56,222: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-01 20:14:56,222: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-01 20:14:56,230: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 20:14:56,230: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 20:14:56,238: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 20:14:56,238: INFO: common: created directory at: artifacts]
[2024-01-01 20:14:56,238: INFO: common: created directory at: artifacts/data_validation]
[2024-01-01 20:14:56,327: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-01 20:14:56,327: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-01 20:14:56,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 20:14:56,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 20:14:56,335: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 20:14:56,335: INFO: common: created directory at: artifacts]
[2024-01-01 20:14:56,335: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-01 20:14:56,967: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-01 20:14:56,967: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-01 20:14:56,967: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-01 20:14:56,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 20:14:56,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 20:14:56,991: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 20:14:56,991: INFO: common: created directory at: artifacts]
[2024-01-01 20:14:56,991: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-01 20:14:57,073: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-01 23:27:26,884: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 23:27:26,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 23:27:26,898: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 23:27:26,898: INFO: common: created directory at: artifacts]
[2024-01-01 23:27:26,898: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-01 23:28:44,252: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 23:28:44,254: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 23:28:44,263: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 23:28:44,263: INFO: common: created directory at: artifacts]
[2024-01-01 23:28:44,263: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-01 23:30:00,485: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 23:30:00,485: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 23:30:00,493: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 23:30:00,493: INFO: common: created directory at: artifacts]
[2024-01-01 23:30:00,493: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-01 23:31:48,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 23:31:48,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 23:31:48,035: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 23:31:48,035: INFO: common: created directory at: artifacts]
[2024-01-01 23:31:48,035: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:10:35,678: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-02 00:10:35,678: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-02 00:10:41,612: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-02 00:10:41,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:41,618: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:41,619: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:10:41,619: INFO: common: created directory at: artifacts]
[2024-01-02 00:10:41,621: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-02 00:10:43,115: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4312:63A2:125D520:16B11DB:6593072A
Accept-Ranges: bytes
Date: Mon, 01 Jan 2024 18:40:43 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10249-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1704134443.781222,VS0,VE329
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 1056ca8f4188f6ce3a4cf1ed00f3174e60565951
Expires: Mon, 01 Jan 2024 18:45:43 GMT
Source-Age: 0

]
[2024-01-02 00:10:43,133: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-02 00:10:43,133: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-02 00:10:43,136: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:43,140: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:43,141: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:10:43,143: INFO: common: created directory at: artifacts]
[2024-01-02 00:10:43,143: INFO: common: created directory at: artifacts/data_validation]
[2024-01-02 00:10:43,196: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-02 00:10:43,196: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-02 00:10:43,204: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:43,206: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:43,208: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:10:43,208: INFO: common: created directory at: artifacts]
[2024-01-02 00:10:43,210: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 00:10:43,708: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-02 00:10:43,709: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-02 00:10:43,709: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-02 00:10:43,713: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:43,716: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:43,718: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:10:43,719: INFO: common: created directory at: artifacts]
[2024-01-02 00:10:43,719: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-02 00:10:43,806: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-02 00:10:43,806: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-02 00:10:43,809: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:43,812: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:10:43,815: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:10:43,815: INFO: common: created directory at: artifacts]
[2024-01-02 00:10:43,816: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:10:45,021: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-02 00:12:10,858: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-02 00:12:10,859: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-02 00:12:14,123: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-02 00:12:14,126: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,128: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,130: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:12:14,131: INFO: common: created directory at: artifacts]
[2024-01-02 00:12:14,131: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-02 00:12:14,131: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-02 00:12:14,135: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-02 00:12:14,135: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-02 00:12:14,137: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,140: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,142: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:12:14,142: INFO: common: created directory at: artifacts]
[2024-01-02 00:12:14,142: INFO: common: created directory at: artifacts/data_validation]
[2024-01-02 00:12:14,177: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-02 00:12:14,177: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-02 00:12:14,181: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,183: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,186: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:12:14,187: INFO: common: created directory at: artifacts]
[2024-01-02 00:12:14,188: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 00:12:14,592: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-02 00:12:14,592: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-02 00:12:14,592: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-02 00:12:14,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,600: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:12:14,601: INFO: common: created directory at: artifacts]
[2024-01-02 00:12:14,601: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-02 00:12:14,654: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-02 00:12:14,654: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-02 00:12:14,657: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,661: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:12:14,664: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:12:14,665: INFO: common: created directory at: artifacts]
[2024-01-02 00:12:14,665: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:12:15,811: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-02 00:15:21,882: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:15:21,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:15:21,888: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:15:21,891: INFO: common: created directory at: artifacts]
[2024-01-02 00:15:21,893: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:17:46,208: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:17:46,213: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:17:46,217: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:17:46,219: INFO: common: created directory at: artifacts]
[2024-01-02 00:17:46,222: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:18:40,990: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:18:40,994: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:18:40,997: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:18:40,999: INFO: common: created directory at: artifacts]
[2024-01-02 00:18:41,000: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:18:42,026: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2024-01-02 00:23:30,259: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-02 00:23:30,259: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-02 00:23:33,252: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-02 00:23:33,252: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:33,252: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:33,252: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:23:33,252: INFO: common: created directory at: artifacts]
[2024-01-02 00:23:33,252: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-02 00:23:34,755: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4312:63A2:125D520:16B11DB:6593072A
Accept-Ranges: bytes
Date: Mon, 01 Jan 2024 18:53:34 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10251-MAA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1704135214.447570,VS0,VE300
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 598e61e8f3826d22ebe2207b15c70c75899eefe1
Expires: Mon, 01 Jan 2024 18:58:34 GMT
Source-Age: 0

]
[2024-01-02 00:23:34,771: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-02 00:23:34,771: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-02 00:23:34,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:34,775: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:34,779: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:23:34,780: INFO: common: created directory at: artifacts]
[2024-01-02 00:23:34,780: INFO: common: created directory at: artifacts/data_validation]
[2024-01-02 00:23:34,813: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-02 00:23:34,813: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-02 00:23:34,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:34,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:34,821: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:23:34,829: INFO: common: created directory at: artifacts]
[2024-01-02 00:23:34,829: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 00:23:35,275: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-02 00:23:35,275: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-02 00:23:35,275: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-02 00:23:35,275: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:35,275: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:35,275: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:23:35,275: INFO: common: created directory at: artifacts]
[2024-01-02 00:23:35,275: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-02 00:23:35,355: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-02 00:23:35,355: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-02 00:23:35,355: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:35,363: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:23:35,363: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:23:35,363: INFO: common: created directory at: artifacts]
[2024-01-02 00:23:35,363: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:23:36,437: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-02 00:27:01,784: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-02 00:27:01,784: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-02 00:27:04,826: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-02 00:27:04,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:04,831: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:04,833: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:27:04,834: INFO: common: created directory at: artifacts]
[2024-01-02 00:27:04,834: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-02 00:27:04,834: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-02 00:27:04,838: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-02 00:27:04,838: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-02 00:27:04,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:04,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:04,847: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:27:04,848: INFO: common: created directory at: artifacts]
[2024-01-02 00:27:04,848: INFO: common: created directory at: artifacts/data_validation]
[2024-01-02 00:27:04,888: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-02 00:27:04,888: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-02 00:27:04,891: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:04,893: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:04,895: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:27:04,896: INFO: common: created directory at: artifacts]
[2024-01-02 00:27:04,896: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 00:27:05,287: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-02 00:27:05,288: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-02 00:27:05,289: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-02 00:27:05,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:05,293: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:05,295: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:27:05,295: INFO: common: created directory at: artifacts]
[2024-01-02 00:27:05,295: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-02 00:27:05,350: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-02 00:27:05,350: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-02 00:27:05,353: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:05,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:27:05,357: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:27:05,358: INFO: common: created directory at: artifacts]
[2024-01-02 00:27:05,358: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:27:06,416: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-02 00:31:01,529: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-02 00:31:01,529: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-02 00:31:04,829: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-02 00:31:04,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:04,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:04,829: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:31:04,829: INFO: common: created directory at: artifacts]
[2024-01-02 00:31:04,829: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-02 00:31:04,829: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-02 00:31:04,845: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-02 00:31:04,845: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-02 00:31:04,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:04,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:04,845: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:31:04,845: INFO: common: created directory at: artifacts]
[2024-01-02 00:31:04,845: INFO: common: created directory at: artifacts/data_validation]
[2024-01-02 00:31:04,877: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-02 00:31:04,877: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-02 00:31:04,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:04,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:04,892: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:31:04,892: INFO: common: created directory at: artifacts]
[2024-01-02 00:31:04,892: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 00:31:05,301: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-02 00:31:05,301: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-02 00:31:05,301: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-02 00:31:05,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:05,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:05,316: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:31:05,316: INFO: common: created directory at: artifacts]
[2024-01-02 00:31:05,316: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-02 00:31:05,379: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-02 00:31:05,379: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-02 00:31:05,380: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:05,380: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:31:05,380: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:31:05,380: INFO: common: created directory at: artifacts]
[2024-01-02 00:31:05,380: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:31:06,538: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-02 00:34:02,927: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-02 00:34:02,927: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-02 00:34:05,985: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-02 00:34:05,987: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:05,990: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:05,991: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:34:05,992: INFO: common: created directory at: artifacts]
[2024-01-02 00:34:05,992: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-02 00:34:05,992: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-02 00:34:05,995: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-02 00:34:05,995: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-02 00:34:05,998: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:06,000: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:06,002: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:34:06,003: INFO: common: created directory at: artifacts]
[2024-01-02 00:34:06,003: INFO: common: created directory at: artifacts/data_validation]
[2024-01-02 00:34:06,048: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-02 00:34:06,048: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-02 00:34:06,052: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:06,056: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:06,058: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:34:06,058: INFO: common: created directory at: artifacts]
[2024-01-02 00:34:06,059: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 00:34:06,465: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-02 00:34:06,466: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-02 00:34:06,466: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-02 00:34:06,466: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:06,466: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:06,466: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:34:06,466: INFO: common: created directory at: artifacts]
[2024-01-02 00:34:06,466: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-02 00:34:06,530: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-02 00:34:06,530: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-02 00:34:06,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:06,536: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:34:06,539: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:34:06,540: INFO: common: created directory at: artifacts]
[2024-01-02 00:34:06,540: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:34:07,712: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-02 00:35:49,228: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-02 00:35:49,228: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-02 00:35:52,449: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-02 00:35:52,451: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,455: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:35:52,456: INFO: common: created directory at: artifacts]
[2024-01-02 00:35:52,456: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-02 00:35:52,456: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-02 00:35:52,460: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-02 00:35:52,460: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-02 00:35:52,463: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,465: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,467: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:35:52,468: INFO: common: created directory at: artifacts]
[2024-01-02 00:35:52,468: INFO: common: created directory at: artifacts/data_validation]
[2024-01-02 00:35:52,492: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-02 00:35:52,492: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-02 00:35:52,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,513: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:35:52,513: INFO: common: created directory at: artifacts]
[2024-01-02 00:35:52,514: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 00:35:52,912: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-02 00:35:52,913: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-02 00:35:52,913: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-02 00:35:52,916: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,918: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,920: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:35:52,920: INFO: common: created directory at: artifacts]
[2024-01-02 00:35:52,921: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-02 00:35:52,978: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-02 00:35:52,978: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-02 00:35:52,981: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,984: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:35:52,986: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:35:52,987: INFO: common: created directory at: artifacts]
[2024-01-02 00:35:52,987: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:35:54,214: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-02 00:37:47,700: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-02 00:37:47,700: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-02 00:37:50,733: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-02 00:37:50,733: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:50,739: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:50,739: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:37:50,739: INFO: common: created directory at: artifacts]
[2024-01-02 00:37:50,739: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-02 00:37:50,739: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-02 00:37:50,739: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-02 00:37:50,739: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-02 00:37:50,739: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:50,755: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:50,755: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:37:50,755: INFO: common: created directory at: artifacts]
[2024-01-02 00:37:50,755: INFO: common: created directory at: artifacts/data_validation]
[2024-01-02 00:37:50,786: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-02 00:37:50,786: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-02 00:37:50,786: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:50,786: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:50,802: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:37:50,802: INFO: common: created directory at: artifacts]
[2024-01-02 00:37:50,802: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 00:37:51,194: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-02 00:37:51,194: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-02 00:37:51,194: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-02 00:37:51,194: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:51,194: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:51,194: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:37:51,210: INFO: common: created directory at: artifacts]
[2024-01-02 00:37:51,210: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-02 00:37:51,256: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-02 00:37:51,256: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-02 00:37:51,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:51,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 00:37:51,256: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 00:37:51,256: INFO: common: created directory at: artifacts]
[2024-01-02 00:37:51,256: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 00:37:52,337: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-02 01:01:12,962: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-02 01:01:12,962: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-02 01:01:16,634: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-02 01:01:16,642: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:16,642: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:16,651: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 01:01:16,651: INFO: common: created directory at: artifacts]
[2024-01-02 01:01:16,651: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-02 01:01:16,651: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-02 01:01:16,659: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-02 01:01:16,659: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-02 01:01:16,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:16,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:16,667: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 01:01:16,667: INFO: common: created directory at: artifacts]
[2024-01-02 01:01:16,667: INFO: common: created directory at: artifacts/data_validation]
[2024-01-02 01:01:16,700: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-02 01:01:16,700: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-02 01:01:16,700: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:16,715: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:16,715: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 01:01:16,715: INFO: common: created directory at: artifacts]
[2024-01-02 01:01:16,715: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 01:01:17,090: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-02 01:01:17,090: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-02 01:01:17,090: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-02 01:01:17,090: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:17,106: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:17,106: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 01:01:17,106: INFO: common: created directory at: artifacts]
[2024-01-02 01:01:17,106: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-02 01:01:17,168: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-02 01:01:17,168: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-02 01:01:17,168: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:17,168: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 01:01:17,168: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 01:01:17,168: INFO: common: created directory at: artifacts]
[2024-01-02 01:01:17,168: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-02 01:01:18,466: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2024-01-02 01:01:28,045: INFO: main: >>>>>>>>> stage Model Evaluation stage completed <<<<<<<<<\n=============x]
[2024-01-02 22:45:08,482: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 22:45:08,490: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 22:45:08,515: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 22:45:08,515: INFO: common: created directory at: artifacts]
[2024-01-02 22:45:08,515: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 22:45:36,940: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 22:45:36,945: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 22:45:36,949: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 22:45:36,952: INFO: common: created directory at: artifacts]
[2024-01-02 22:45:36,953: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 22:47:38,703: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 22:47:38,708: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-02 22:47:38,712: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-02 22:47:38,714: INFO: common: created directory at: artifacts]
[2024-01-02 22:47:38,717: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-02 22:47:39,389: INFO: 1952387798: Data split and balanced successfully.]
[2024-01-02 23:53:21,018: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.133:8080]
[2024-01-02 23:53:21,018: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-01-02 23:53:21,050: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-02 23:53:23,053: WARNING: _internal:  * Debugger is active!]
[2024-01-02 23:53:23,069: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-02 23:54:38,362: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\flask\\app.py', reloading]
[2024-01-02 23:54:38,378: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\flask\\templating.py', reloading]
[2024-01-02 23:54:38,379: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\jinja2\\environment.py', reloading]
[2024-01-02 23:54:38,385: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\werkzeug\\routing\\map.py', reloading]
[2024-01-02 23:54:38,387: INFO: _internal: 127.0.0.1 - - [02/Jan/2024 23:54:38] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2024-01-02 23:54:38,498: INFO: _internal: 127.0.0.1 - - [02/Jan/2024 23:54:38] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -]
[2024-01-02 23:54:38,498: INFO: _internal: 127.0.0.1 - - [02/Jan/2024 23:54:38] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -]
[2024-01-02 23:54:38,549: INFO: _internal: 127.0.0.1 - - [02/Jan/2024 23:54:38] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -]
[2024-01-02 23:54:38,562: INFO: _internal: 127.0.0.1 - - [02/Jan/2024 23:54:38] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -]
[2024-01-02 23:54:39,610: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-02 23:54:41,685: WARNING: _internal:  * Debugger is active!]
[2024-01-02 23:54:41,689: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-02 23:55:00,173: INFO: _internal: 192.168.0.133 - - [02/Jan/2024 23:55:00] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2024-01-02 23:55:00,305: INFO: _internal: 192.168.0.133 - - [02/Jan/2024 23:55:00] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -]
[2024-01-02 23:55:00,308: INFO: _internal: 192.168.0.133 - - [02/Jan/2024 23:55:00] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -]
[2024-01-02 23:55:00,352: INFO: _internal: 192.168.0.133 - - [02/Jan/2024 23:55:00] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -]
[2024-01-02 23:55:00,367: INFO: _internal: 192.168.0.133 - - [02/Jan/2024 23:55:00] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -]
[2024-01-02 23:55:37,551: INFO: _internal: 192.168.0.133 - - [02/Jan/2024 23:55:37] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -]
[2024-01-02 23:58:52,615: INFO: _internal: 127.0.0.1 - - [02/Jan/2024 23:58:52] "GET / HTTP/1.1" 200 -]
[2024-01-02 23:58:53,023: INFO: _internal: 127.0.0.1 - - [02/Jan/2024 23:58:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-01-02 23:58:57,858: INFO: _internal: 192.168.0.133 - - [02/Jan/2024 23:58:57] "GET / HTTP/1.1" 200 -]
[2024-01-02 23:58:58,084: INFO: _internal: 192.168.0.133 - - [02/Jan/2024 23:58:58] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-01-02 23:59:13,155: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.133:8080]
[2024-01-02 23:59:13,155: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-01-02 23:59:13,155: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-02 23:59:15,187: WARNING: _internal:  * Debugger is active!]
[2024-01-02 23:59:15,187: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 00:05:06,593: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:05:06] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 00:05:14,379: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:05:14] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 00:06:24,156: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:06:24] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 00:06:32,019: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:06:32] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 00:12:57,228: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:12:57,229: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:12:57,231: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:12:57,232: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:12:58,515: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 00:13:00,749: WARNING: _internal:  * Debugger is active!]
[2024-01-03 00:13:00,749: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 00:14:19,344: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:14:19] "GET / HTTP/1.1" 200 -]
[2024-01-03 00:15:13,097: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:15:13] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 00:17:22,749: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:17:22,751: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:17:22,751: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:17:24,042: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 00:17:26,265: WARNING: _internal:  * Debugger is active!]
[2024-01-03 00:17:26,281: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 00:17:35,165: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:17:35] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 00:19:57,541: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:19:57,543: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:19:57,543: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:19:58,844: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 00:20:01,094: WARNING: _internal:  * Debugger is active!]
[2024-01-03 00:20:01,095: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 00:20:05,731: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:20:05] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 00:20:16,479: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:20:16] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 00:21:24,060: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:21:24,061: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:21:24,062: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\app.py', reloading]
[2024-01-03 00:21:25,348: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 00:21:27,510: WARNING: _internal:  * Debugger is active!]
[2024-01-03 00:21:27,513: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 00:21:30,743: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 00:21:30] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 00:24:25,112: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\src\\vifd\\components\\data_transformation.py', reloading]
[2024-01-03 00:24:25,113: INFO: _internal:  * Detected change in 'd:\\vehicle_insurance_fraud_detection\\src\\vifd\\components\\data_transformation.py', reloading]
[2024-01-03 00:24:25,192: INFO: _internal:  * Detected change in 'd:\\vehicle_insurance_fraud_detection\\src\\vifd\\__init__.py', reloading]
[2024-01-03 00:24:25,192: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\src\\vifd\\__init__.py', reloading]
[2024-01-03 00:24:26,475: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 00:24:28,730: WARNING: _internal:  * Debugger is active!]
[2024-01-03 00:24:28,746: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 00:24:38,140: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\deprecations.py', reloading]
[2024-01-03 00:24:38,140: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\models\\enums.py', reloading]
[2024-01-03 00:24:38,155: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\gateways\\disk\\create.py', reloading]
[2024-01-03 00:24:38,155: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\core\\prefix_data.py', reloading]
[2024-01-03 00:24:38,171: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\history.py', reloading]
[2024-01-03 00:24:38,171: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\core\\solve.py', reloading]
[2024-01-03 00:24:38,187: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\plugins\\types.py', reloading]
[2024-01-03 00:24:38,187: INFO: _internal:  * Detected change in 'd:\\vehicle_insurance_fraud_detection\\src\\vifd\\constants\\__init__.py', reloading]
[2024-01-03 00:24:38,187: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\src\\vifd\\constants\\__init__.py', reloading]
[2024-01-03 00:24:38,203: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\plugins\\hookspec.py', reloading]
[2024-01-03 00:24:38,252: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\plugins\\__init__.py', reloading]
[2024-01-03 00:24:38,270: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\base\\context.py', reloading]
[2024-01-03 00:24:38,274: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\cli\\conda_argparse.py', reloading]
[2024-01-03 00:24:38,274: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\cli\\main.py', reloading]
[2024-01-03 00:24:38,274: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Lib\\site-packages\\conda\\exception_handler.py', reloading]
[2024-01-03 00:24:40,192: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 00:24:42,770: WARNING: _internal:  * Debugger is active!]
[2024-01-03 00:24:42,770: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 00:55:44,326: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\src\\vifd\\utils\\common.py', reloading]
[2024-01-03 00:55:44,328: INFO: _internal:  * Detected change in 'd:\\vehicle_insurance_fraud_detection\\src\\vifd\\utils\\common.py', reloading]
[2024-01-03 00:55:45,574: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 00:55:47,885: WARNING: _internal:  * Debugger is active!]
[2024-01-03 00:55:47,893: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 00:56:15,433: INFO: _internal:  * Detected change in 'd:\\vehicle_insurance_fraud_detection\\src\\vifd\\utils\\common.py', reloading]
[2024-01-03 00:56:15,433: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\src\\vifd\\utils\\common.py', reloading]
[2024-01-03 00:56:15,434: INFO: _internal:  * Detected change in 'd:\\vehicle_insurance_fraud_detection\\src\\vifd\\utils\\common.py', reloading]
[2024-01-03 00:56:15,435: INFO: _internal:  * Detected change in 'd:\\vehicle_insurance_fraud_detection\\src\\vifd\\utils\\common.py', reloading]
[2024-01-03 00:56:15,435: INFO: _internal:  * Detected change in 'D:\\vehicle_insurance_fraud_detection\\src\\vifd\\utils\\common.py', reloading]
[2024-01-03 00:56:16,809: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 00:56:19,077: WARNING: _internal:  * Debugger is active!]
[2024-01-03 00:56:19,077: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 00:56:23,900: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 00:56:23,903: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 00:56:23,910: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-03 00:56:23,913: INFO: common: created directory at: artifacts]
[2024-01-03 00:56:23,915: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-03 01:01:43,910: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:01:43,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:01:43,918: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-03 01:01:43,920: INFO: common: created directory at: artifacts]
[2024-01-03 01:01:43,921: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-03 01:02:23,233: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:02:23,237: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:02:23,240: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-03 01:02:23,242: INFO: common: created directory at: artifacts]
[2024-01-03 01:02:23,243: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-03 01:08:10,512: INFO: _internal:  * Detected change in 'C:\\Users\\Lahari\\anaconda3\\Scripts\\conda-script.py', reloading]
[2024-01-03 01:08:12,732: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 01:08:16,491: WARNING: _internal:  * Debugger is active!]
[2024-01-03 01:08:16,498: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 01:08:52,199: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:08:52,200: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:08:52,207: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-03 01:08:52,209: INFO: common: created directory at: artifacts]
[2024-01-03 01:08:52,211: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-03 01:10:10,602: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:10:10,606: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:10:10,609: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-03 01:10:10,611: INFO: common: created directory at: artifacts]
[2024-01-03 01:10:10,612: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-03 01:10:50,355: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:10:50,359: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:10:50,362: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-03 01:10:50,364: INFO: common: created directory at: artifacts]
[2024-01-03 01:10:50,366: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-03 01:18:28,438: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:18:28,442: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:18:28,446: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-03 01:18:28,448: INFO: common: created directory at: artifacts]
[2024-01-03 01:18:28,449: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-03 01:20:10,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:20:10,688: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 01:20:10,692: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-03 01:20:10,694: INFO: common: created directory at: artifacts]
[2024-01-03 01:20:10,695: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-03 01:20:11,145: INFO: 2473958874: Data split and balanced successfully.]
[2024-01-03 01:20:41,604: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.133:8080]
[2024-01-03 01:20:41,604: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-01-03 01:20:41,604: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2024-01-03 01:20:43,577: WARNING: _internal:  * Debugger is active!]
[2024-01-03 01:20:43,577: INFO: _internal:  * Debugger PIN: 321-935-171]
[2024-01-03 01:20:53,439: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 01:20:53] "POST /predict HTTP/1.1" 200 -]
[2024-01-03 01:21:40,582: INFO: _internal: 127.0.0.1 - - [03/Jan/2024 01:21:40] "POST /predict HTTP/1.1" 200 -]
[2024-01-04 02:05:37,862: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.133:8080]
[2024-01-04 02:05:37,862: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-01-04 17:48:12,798: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.133:8080]
[2024-01-04 17:48:12,802: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-01-04 17:48:32,868: INFO: _internal: 127.0.0.1 - - [04/Jan/2024 17:48:32] "GET / HTTP/1.1" 200 -]
[2024-01-04 17:48:32,940: INFO: _internal: 127.0.0.1 - - [04/Jan/2024 17:48:32] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-01-04 17:49:32,723: INFO: _internal: 127.0.0.1 - - [04/Jan/2024 17:49:32] "POST /predict HTTP/1.1" 200 -]
[2024-01-04 19:14:47,654: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 19:14:47,654: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 19:14:54,087: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 19:14:54,118: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:54,118: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:54,133: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:14:54,133: INFO: common: created directory at: artifacts]
[2024-01-04 19:14:54,133: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 19:14:54,133: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-04 19:14:54,165: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 19:14:54,165: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 19:14:54,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:54,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:54,180: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:14:54,180: INFO: common: created directory at: artifacts]
[2024-01-04 19:14:54,180: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 19:14:54,274: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 19:14:54,274: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 19:14:54,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:54,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:54,290: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:14:54,290: INFO: common: created directory at: artifacts]
[2024-01-04 19:14:54,290: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 19:14:54,951: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 19:14:54,951: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 19:14:54,951: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 19:14:54,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:54,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:54,951: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:14:54,951: INFO: common: created directory at: artifacts]
[2024-01-04 19:14:54,951: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 19:14:55,077: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 19:14:55,077: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 19:14:55,077: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:55,077: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:14:55,077: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:14:55,077: INFO: common: created directory at: artifacts]
[2024-01-04 19:14:55,092: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 19:14:55,549: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2024-01-04 19:15:03,349: INFO: main: >>>>>>>>> stage Model Evaluation stage completed <<<<<<<<<\n=============x]
[2024-01-04 19:18:36,881: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 19:18:36,881: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 19:18:41,218: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 19:18:41,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,227: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,227: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:18:41,227: INFO: common: created directory at: artifacts]
[2024-01-04 19:18:41,227: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 19:18:41,227: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-04 19:18:41,235: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 19:18:41,235: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 19:18:41,235: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,235: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,243: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:18:41,243: INFO: common: created directory at: artifacts]
[2024-01-04 19:18:41,243: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 19:18:41,292: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 19:18:41,292: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 19:18:41,302: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,304: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,307: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:18:41,307: INFO: common: created directory at: artifacts]
[2024-01-04 19:18:41,307: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 19:18:41,821: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 19:18:41,821: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 19:18:41,822: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 19:18:41,822: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,822: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,828: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:18:41,828: INFO: common: created directory at: artifacts]
[2024-01-04 19:18:41,828: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 19:18:41,900: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 19:18:41,900: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 19:18:41,900: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,908: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:18:41,910: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:18:41,910: INFO: common: created directory at: artifacts]
[2024-01-04 19:18:41,910: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 19:18:43,478: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-04 19:22:59,778: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 19:22:59,778: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 19:23:03,599: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 19:23:03,607: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:03,607: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:03,607: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:23:03,607: INFO: common: created directory at: artifacts]
[2024-01-04 19:23:03,607: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 19:23:03,607: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-04 19:23:03,615: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 19:23:03,615: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 19:23:03,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:03,624: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:03,624: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:23:03,624: INFO: common: created directory at: artifacts]
[2024-01-04 19:23:03,624: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 19:23:03,672: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 19:23:03,672: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 19:23:03,681: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:03,681: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:03,688: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:23:03,688: INFO: common: created directory at: artifacts]
[2024-01-04 19:23:03,688: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 19:23:04,218: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 19:23:04,218: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 19:23:04,218: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 19:23:04,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:04,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:04,226: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:23:04,226: INFO: common: created directory at: artifacts]
[2024-01-04 19:23:04,226: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 19:23:04,323: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 19:23:04,323: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 19:23:04,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:04,333: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 19:23:04,333: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 19:23:04,333: INFO: common: created directory at: artifacts]
[2024-01-04 19:23:04,333: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 19:23:06,235: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-04 20:28:46,515: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 20:28:46,515: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 20:28:50,564: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 20:28:50,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:50,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:50,564: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:28:50,564: INFO: common: created directory at: artifacts]
[2024-01-04 20:28:50,596: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 20:28:52,556: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 71BE:5B35:1B55EEA:228F120:6596C7AA
Accept-Ranges: bytes
Date: Thu, 04 Jan 2024 14:58:50 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10242-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1704380330.380245,VS0,VE338
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6176dda357c0df6af997356d66f2700bfe34fc84
Expires: Thu, 04 Jan 2024 15:03:50 GMT
Source-Age: 0

]
[2024-01-04 20:28:52,586: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 20:28:52,586: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 20:28:52,595: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:52,595: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:52,595: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:28:52,595: INFO: common: created directory at: artifacts]
[2024-01-04 20:28:52,595: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 20:28:52,657: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 20:28:52,657: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 20:28:52,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:52,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:52,673: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:28:52,673: INFO: common: created directory at: artifacts]
[2024-01-04 20:28:52,673: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 20:28:53,229: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 20:28:53,229: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 20:28:53,229: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 20:28:53,229: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:53,229: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:53,244: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:28:53,244: INFO: common: created directory at: artifacts]
[2024-01-04 20:28:53,244: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 20:28:53,322: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 20:28:53,322: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 20:28:53,322: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:53,338: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:28:53,338: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:28:53,338: INFO: common: created directory at: artifacts]
[2024-01-04 20:28:53,338: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 20:28:54,861: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-04 20:37:49,742: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 20:37:49,742: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 20:37:53,629: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 20:37:53,629: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:53,629: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:53,629: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:37:53,629: INFO: common: created directory at: artifacts]
[2024-01-04 20:37:53,629: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 20:37:53,629: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-04 20:37:53,645: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 20:37:53,645: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 20:37:53,645: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:53,653: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:53,653: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:37:53,653: INFO: common: created directory at: artifacts]
[2024-01-04 20:37:53,653: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 20:37:53,710: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 20:37:53,710: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 20:37:53,710: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:53,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:53,718: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:37:53,718: INFO: common: created directory at: artifacts]
[2024-01-04 20:37:53,718: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 20:37:54,188: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 20:37:54,188: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 20:37:54,188: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 20:37:54,188: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:54,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:54,196: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:37:54,196: INFO: common: created directory at: artifacts]
[2024-01-04 20:37:54,196: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 20:37:54,268: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 20:37:54,268: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 20:37:54,276: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:54,276: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:37:54,284: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:37:54,284: INFO: common: created directory at: artifacts]
[2024-01-04 20:37:54,284: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 20:37:55,843: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-04 20:46:40,861: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 20:46:40,861: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 20:46:45,208: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 20:46:45,208: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:45,208: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:45,208: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:46:45,208: INFO: common: created directory at: artifacts]
[2024-01-04 20:46:45,208: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 20:46:47,114: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 71BE:5B35:1B55EEA:228F120:6596C7AA
Accept-Ranges: bytes
Date: Thu, 04 Jan 2024 15:16:45 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10243-MAA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1704381405.836987,VS0,VE301
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 4c6c51258cc363ff856a09bc1b211739add96d37
Expires: Thu, 04 Jan 2024 15:21:45 GMT
Source-Age: 0

]
[2024-01-04 20:46:47,161: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 20:46:47,161: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 20:46:47,161: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:47,177: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:47,177: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:46:47,177: INFO: common: created directory at: artifacts]
[2024-01-04 20:46:47,177: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 20:46:47,224: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 20:46:47,224: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 20:46:47,239: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:47,239: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:47,239: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:46:47,239: INFO: common: created directory at: artifacts]
[2024-01-04 20:46:47,239: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 20:46:47,771: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 20:46:47,771: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 20:46:47,771: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 20:46:47,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:47,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:47,787: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:46:47,787: INFO: common: created directory at: artifacts]
[2024-01-04 20:46:47,787: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 20:46:47,849: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 20:46:47,849: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 20:46:47,865: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:47,865: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:46:47,865: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:46:47,865: INFO: common: created directory at: artifacts]
[2024-01-04 20:46:47,865: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 20:46:49,240: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 374, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 339, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 132, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 178, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 157, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-04 20:49:19,865: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:49:19,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 20:49:19,873: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 20:49:19,881: INFO: common: created directory at: artifacts]
[2024-01-04 20:49:19,881: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 20:49:21,678: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2024-01-04 21:01:07,543: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 21:01:07,543: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 21:01:11,200: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 21:01:11,216: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:11,216: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:11,216: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:01:11,216: INFO: common: created directory at: artifacts]
[2024-01-04 21:01:11,216: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 21:01:13,386: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: 
Connection: close
Content-Length: 68996
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e183ebd6a5b61282c4986b78d0fad9592ad3204a2291140e9b19adf0f43414c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 71BE:5B35:1B55EEA:228F120:6596C7AA
Accept-Ranges: bytes
Date: Thu, 04 Jan 2024 15:31:12 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10231-MAA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1704382272.766044,VS0,VE365
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: fa3a8b1da7e461491ab5bdbcb89d3e6706349f76
Expires: Thu, 04 Jan 2024 15:36:12 GMT
Source-Age: 0

]
[2024-01-04 21:01:13,401: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 21:01:13,401: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 21:01:13,401: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:13,401: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:13,401: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:01:13,401: INFO: common: created directory at: artifacts]
[2024-01-04 21:01:13,401: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 21:01:13,448: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 21:01:13,448: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 21:01:13,448: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:13,448: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:13,448: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:01:13,448: INFO: common: created directory at: artifacts]
[2024-01-04 21:01:13,464: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 21:01:13,896: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 21:01:13,896: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 21:01:13,896: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 21:01:13,898: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:13,900: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:13,902: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:01:13,903: INFO: common: created directory at: artifacts]
[2024-01-04 21:01:13,903: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 21:01:13,970: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 21:01:13,970: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 21:01:13,973: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:13,977: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:01:13,980: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:01:13,981: INFO: common: created directory at: artifacts]
[2024-01-04 21:01:13,981: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 21:01:15,274: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 374, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 339, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 132, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 178, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 157, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-04 21:02:47,933: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 21:02:47,933: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 21:02:50,246: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 21:02:50,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,246: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:02:50,246: INFO: common: created directory at: artifacts]
[2024-01-04 21:02:50,246: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 21:02:50,246: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-04 21:02:50,246: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 21:02:50,246: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 21:02:50,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,246: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:02:50,246: INFO: common: created directory at: artifacts]
[2024-01-04 21:02:50,261: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 21:02:50,277: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 21:02:50,277: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 21:02:50,277: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,293: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,293: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:02:50,293: INFO: common: created directory at: artifacts]
[2024-01-04 21:02:50,293: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 21:02:50,606: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 21:02:50,606: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 21:02:50,606: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 21:02:50,606: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,606: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,606: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:02:50,621: INFO: common: created directory at: artifacts]
[2024-01-04 21:02:50,621: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 21:02:50,653: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 21:02:50,653: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 21:02:50,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:02:50,668: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:02:50,668: INFO: common: created directory at: artifacts]
[2024-01-04 21:02:50,668: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 21:02:51,751: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 374, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 339, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 132, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 178, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 157, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-04 21:08:33,985: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 21:08:33,985: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 21:08:36,235: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 21:08:36,235: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,235: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,235: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:08:36,235: INFO: common: created directory at: artifacts]
[2024-01-04 21:08:36,235: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 21:08:36,235: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-04 21:08:36,251: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 21:08:36,251: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 21:08:36,251: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,251: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,251: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:08:36,251: INFO: common: created directory at: artifacts]
[2024-01-04 21:08:36,251: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 21:08:36,282: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 21:08:36,282: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 21:08:36,282: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,282: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,282: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:08:36,282: INFO: common: created directory at: artifacts]
[2024-01-04 21:08:36,282: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 21:08:36,596: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 21:08:36,596: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 21:08:36,596: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 21:08:36,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,611: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:08:36,611: INFO: common: created directory at: artifacts]
[2024-01-04 21:08:36,611: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 21:08:36,658: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 21:08:36,658: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 21:08:36,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:08:36,658: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:08:36,658: INFO: common: created directory at: artifacts]
[2024-01-04 21:08:36,658: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 21:08:37,613: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\vehicle_insurance_fraud_detection\main.py", line 51, in <module>
    obj.main()
  File "D:\vehicle_insurance_fraud_detection\src\vifd\pipeline\stage_05_model_evaluation.py", line 14, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\vehicle_insurance_fraud_detection\src\vifd\components\model_evaluation.py", line 30, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\fluent.py", line 374, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 339, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 132, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 178, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lahari\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 157, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-01-04 21:22:56,823: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-01-04 21:22:56,823: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-01-04 21:22:59,136: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-04 21:22:59,151: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,151: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,151: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:22:59,151: INFO: common: created directory at: artifacts]
[2024-01-04 21:22:59,151: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-04 21:22:59,151: INFO: data_ingestion: File already exists of size: ~ 67 KB]
[2024-01-04 21:22:59,151: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 21:22:59,151: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-04 21:22:59,151: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,151: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,151: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:22:59,151: INFO: common: created directory at: artifacts]
[2024-01-04 21:22:59,151: INFO: common: created directory at: artifacts/data_validation]
[2024-01-04 21:22:59,183: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-04 21:22:59,183: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-04 21:22:59,183: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,183: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,183: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:22:59,183: INFO: common: created directory at: artifacts]
[2024-01-04 21:22:59,183: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-04 21:22:59,511: INFO: data_transformation: Data split and balanced successfully.]
[2024-01-04 21:22:59,511: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-04 21:22:59,511: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-01-04 21:22:59,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,511: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:22:59,511: INFO: common: created directory at: artifacts]
[2024-01-04 21:22:59,511: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-04 21:22:59,558: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-01-04 21:22:59,558: INFO: main: >>>>>>> stage Model Evaluation stage started <<<<<<<<]
[2024-01-04 21:22:59,558: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,558: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 21:22:59,558: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-04 21:22:59,558: INFO: common: created directory at: artifacts]
[2024-01-04 21:22:59,558: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-04 21:23:00,840: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2024-01-04 21:23:10,921: INFO: main: >>>>>>>>> stage Model Evaluation stage completed <<<<<<<<<\n=============x]
